package com.ehaoyao.opertioncenter.thirdOrderAudit.vo;
// Generated 2016-3-21 18:38:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParamConfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "param_config")
public class ParamConfig implements java.io.Serializable {

	private Long paramConfigId;
	private String paramType;
	private String paramName;
	private String paramValue;
	private String paramStatus;
	private String remark;
	private String lastTime;
	private String createTime;

	public ParamConfig() {
	}

	public ParamConfig(String paramType, String paramName) {
		this.paramType = paramType;
		this.paramName = paramName;
	}

	public ParamConfig(String paramType, String paramName, String paramValue, String paramStatus, String remark,
			String lastTime, String createTime) {
		this.paramType = paramType;
		this.paramName = paramName;
		this.paramValue = paramValue;
		this.paramStatus = paramStatus;
		this.remark = remark;
		this.lastTime = lastTime;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "param_config_id", unique = true, nullable = false)
	public Long getParamConfigId() {
		return this.paramConfigId;
	}

	public void setParamConfigId(Long paramConfigId) {
		this.paramConfigId = paramConfigId;
	}

	@Column(name = "param_type", nullable = false, length = 50)
	public String getParamType() {
		return this.paramType;
	}

	public void setParamType(String paramType) {
		this.paramType = paramType;
	}

	@Column(name = "param_name", nullable = false, length = 20)
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	@Column(name = "param_value", length = 50)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	@Column(name = "param_status", length = 20)
	public String getParamStatus() {
		return this.paramStatus;
	}

	public void setParamStatus(String paramStatus) {
		this.paramStatus = paramStatus;
	}

	@Column(name = "remark", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "last_time", length = 30)
	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
