package com.ehaoyao.opertioncenter.thirdOrderAudit.model;
// Generated 2016-3-4 15:11:40 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InvoiceInfo generated by hbm2java
 */
@Entity
@Table(name = "invoice_info", catalog = "operationscenter")
public class InvoiceInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7164681680585330213L;
	
	private Long invoiceId;
	private String orderNumber;
	private String orderFlag;
    private String kfAccount;
    private String invoiceStatus;
	private String invoiceType;
	private String invoiceTitle;
	private String invoiceContent;
	private String remark;
	private String createTime;

	public InvoiceInfo() {
	}

	public InvoiceInfo(String orderNumber, String orderFlag) {
		this.orderNumber = orderNumber;
		this.orderFlag = orderFlag;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_id", unique = true, nullable = false)
	public Long getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "order_number", nullable = false, length = 50)
	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "order_flag", nullable = false, length = 20)
	public String getOrderFlag() {
		return this.orderFlag;
	}

	public void setOrderFlag(String orderFlag) {
		this.orderFlag = orderFlag;
	}
	
	@Column(name = "kf_account", length = 50)
	public String getKfAccount() {
		return kfAccount;
	}

	public void setKfAccount(String kfAccount) {
		this.kfAccount = kfAccount;
	}
	
	@Column(name = "invoice_status", length = 20)
	public String getInvoiceStatus() {
		return invoiceStatus;
	}

	public void setInvoiceStatus(String invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	@Column(name = "invoice_type", length = 20)
	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	@Column(name = "invoice_title", length = 50)
	public String getInvoiceTitle() {
		return this.invoiceTitle;
	}

	public void setInvoiceTitle(String invoiceTitle) {
		this.invoiceTitle = invoiceTitle;
	}

	@Column(name = "invoice_content", length = 500)
	public String getInvoiceContent() {
		return this.invoiceContent;
	}

	public void setInvoiceContent(String invoiceContent) {
		this.invoiceContent = invoiceContent;
	}

	@Column(name = "remark", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
