package com.ehaoyao.opertioncenter.thirdOrderAudit.model;
// Generated 2016-1-11 1:31:23 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderInfo generated by hbm2java
 */
@Entity
@Table(name = "order_info")
public class OrderInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7318950268435146384L;
	
	/**------------------------订单审核状态码----------------------------*/
	/**
	 * 等待客服审核
	 */
	public static final String ORDER_AUDIT_STATUS_WAIT = "WAIT";
	
	/**
	 * 客服审核通过
	 */
	public static final String ORDER_AUDIT_STATUS_PRESUCC = "PRESUCC"; 
	/**
	 * 客服审核驳回
	 */
	public static final String ORDER_AUDIT_STATUS_PRERETURN = "PRERETURN";
	
	/**
	 * 医师审核通过
	 */
	public static final String ORDER_AUDIT_STATUS_SUCC = "SUCC"; 
	/**
	 * 医师审核驳回
	 */
	public static final String ORDER_AUDIT_STATUS_RETURN = "RETURN";
	/**
	 * 作废
	 */
	public static final String ORDER_AUDIT_STATUS_VOID = "VOID";
	/**
	 * 取消审核
	 */
	public static final String ORDER_AUDIT_STATUS_CANCEL = "CANCEL"; 
	
	/**------------------------订单状态码----------------------------*/

	
	
	/**------------------------付款状态枚举----------------------------*/
	/**
	 * 未付款
	 */
	public static final String ORDER_PAY_STATUS_NOPAY = "NOPAY";
	/**
	 * 已付款
	 */
	public static final String ORDER_PAY_STATUS_PAID = "PAID";
	
	/**------------------------支付方式枚举----------------------------*/
	/**
	 * COD:货到付款  
	 */
	public static final String ORDER_PAY_TYPE_COD = "COD";
	/**
	 * ONLINEPAY:网上支付
	 */
	public static final String ORDER_PAY_TYPE_ONLINEPAY = "ONLINEPAY";
	
	
	
	/**------------------------开票状态枚举----------------------------*/
	/**
	 * 开发票
	 */
	public static final String ORDER_INVOICE_STATUS_YES = "1";
	/**
	 * 不开发票
	 */
	public static final String ORDER_INVOICE_STATUS_NO = "0";

	/**------------------------发票类型枚举----------------------------*/
	/**
	 * 普通发票
	 */
	public static final String ORDER_INVOICE_TYPE_PLAIN = "PLAIN";
	/**
	 * 电子发票
	 */
	public static final String ORDER_INVOICE_TYPE_ELECTRONIC = "ELECTRONIC";
	/**
	 * 增值税发票
	 */
	public static final String ORDER_INVOICE_TYPE_VAT = "VAT";
	
	
	/**------------------------订单渠道名称枚举----------------------------*/
	/**
	 * 天猫处方药
	 */
	public static final String ORDER_ORDER_FLAG_TMCFY = "TMCFY";
	
	/**
	 * 平安
	 */
	public static final String ORDER_ORDER_FLAG_PA = "PACFY";
	
	/**
	 * 掌上糖医
	 */
	public static final String ORDER_ORDER_FLAG_ZSTY = "ZSTY";
	
	/**
	 * 360处方药
	 */
	public static final String ORDER_ORDER_FLAG_360CFY = "SLLCFY";
	
	
	
	
	/**
	 * 订单表主键
	 */
    private Long orderId;

    /**
     * 订单编号
     */
    private String orderNumber;

    /**
     * 订单标识(渠道标识) 天猫:TMCFY  ...
     */
    private String orderFlag;

    /**
     * 下单用户id
     */
    private String userId;

    /**
     * 下单用户编码
     */
    private String userCode;

    /**
     * 下单用户名
     */
    private String nickName;

    /**
     * 下单用户姓名
     */
    private String userName;

    /**
     * 处方类型   0:不是  1:是
     */
    private Character prescriptionType;

    /**
     * 订单状态   UNTREATED:未处理  FINISH:已完成(目前用于中药馆煎药中心人员,订单是否已处理 )
     */
    private String orderStatus;

    /**
     * 审核状态  WAIT:待审核 PRESUCC:客服审核通过 PRERETURN:客服审核驳回  SUCC:医师审核通过  RETURN:医师审核驳回 VOID:作废  CANCEL:取消
     */
    private String auditStatus;
    
    /**
     * 发票状态  0：不开发票  1：开发票
     */
    private String invoiceStatus;
    

    /**
     * 付款状态  NOPAY:未付款   PAID:已付款   RETURN:已退款
     */
    private String payStatus;

    /**
     * 下单类型  CUSORDER:客户下单(客户自选药品)   REPORDER:代下单(客户上传处方单图片)
     */
    private String orderType;

    /**
     * 支付类型 COD:货到付款  ONLINEPAY:网上支付...
     */
    private String payType;

    /**
     * 订单时间
     */
    private String orderTime;
   

    /**
     * 收货人
     */
    private String receiver;


    /**
     * 患者姓名
     */
    private String patientName;

    /**
     * 性别 男：MALE  女：FAMALE
     */
    private String sex;

    /**
     * 年龄
     */
    private Integer age;

    /**
     * 是否孕妇  0: 不是  1:是
     */
    private Character pregnantFlag;

    /**
     * 是否代煎  0:否 1:是
     */
    private Character decoctFlag;

    /**
     * 剂量
     */
    private String dose;

    /**
     * 小图片链接
     */
    private String smallPicLink;

    /**
     * 大图链接
     */
    private String bigPicLink;

    /**
     * 付款时间
     */
    private String paymentTime;


    /**
     * 送货日期
     */
    private String deliveryDate;
	
	/**
     * 医院处方日期
     */
	private String hospitalPrescDate;

    /**
     * 详细地址
     */
    private String addressDetail;

    /**
     * 手机号码
     */
    private String mobile;

    /**
     * 联系电话
     */
    private String telephone;

    /**
     * 省份
     */
    private String province;

    /**
     * 城市
     */
    private String city;
    
    /**
     * 区域
     */
    private String area;

    /**
     * 国家
     */
    private String country;
	
	/**
     * 实际支付金额（商品总价格+邮费-订单优惠金额）
     */
    private BigDecimal price;

    /**
     * 订单总金额（商品总价格+邮费）
     */
    private BigDecimal orderPrice;

    /**
     * 优惠金额
     */
    private BigDecimal discountAmount;
	
	/**
     * 满反满送
     */
	private BigDecimal overReturnFree;

	/**
     * 快递费用
     */
    private BigDecimal expressPrice;

	/**
     * 平台支付金额
     */
    private BigDecimal platPayPrice;

    /**
     * 使用说明（用药说明）
     */
    private String instructions;


    /**
     * 备注
     */
    private String remark;

    /**
     * 币种  RMB人民币、USD美元、EUR欧元、HKD港币、GBP英镑、JPY日元、KRW韩元、CAD加元、AUD澳元、CHF瑞郎、SGD新加坡元、MYR马来西亚币、IDR印尼、NZD新西兰、VND越南、THB泰铢、PHP菲律宾
     */
    private String feeType;

    /**
     * 最后操作时间 
     */
    private String lastTime;

    /**
     * 创建时间
     */
    private String createTime;
    

	public OrderInfo() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_number", nullable = false, length = 50)
	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "order_flag", nullable = false, length = 10)
	public String getOrderFlag() {
		return this.orderFlag;
	}

	public void setOrderFlag(String orderFlag) {
		this.orderFlag = orderFlag;
	}

	@Column(name = "user_id", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_code", length = 50)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	@Column(name = "nick_name", length = 50)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "prescription_type", length = 1)
	public Character getPrescriptionType() {
		return this.prescriptionType;
	}

	public void setPrescriptionType(Character prescriptionType) {
		this.prescriptionType = prescriptionType;
	}

	@Column(name = "order_status", length = 20)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "audit_status", length = 20)
	public String getAuditStatus() {
		return this.auditStatus;
	}

	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}
	
	
	@Column(name = "invoice_status", length = 20)
	public String getInvoiceStatus() {
		return invoiceStatus;
	}


	public void setInvoiceStatus(String invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}


	@Column(name = "pay_status", length = 20)
	public String getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	@Column(name = "order_type", length = 20)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "pay_type", length = 20)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "order_time", nullable = false, length = 30)
	public String getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(String orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "price", nullable = false, precision = 13, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "receiver", nullable = false, length = 50)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "patient_name", length = 50)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "sex", length = 10)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "pregnant_flag", length = 1)
	public Character getPregnantFlag() {
		return this.pregnantFlag;
	}

	public void setPregnantFlag(Character pregnantFlag) {
		this.pregnantFlag = pregnantFlag;
	}

	@Column(name = "decoct_flag", length = 1)
	public Character getDecoctFlag() {
		return this.decoctFlag;
	}

	public void setDecoctFlag(Character decoctFlag) {
		this.decoctFlag = decoctFlag;
	}

	@Column(name = "dose", length = 20)
	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

	@Column(name = "small_pic_link", length = 200)
	public String getSmallPicLink() {
		return this.smallPicLink;
	}

	public void setSmallPicLink(String smallPicLink) {
		this.smallPicLink = smallPicLink;
	}

	@Column(name = "big_pic_link", length = 200)
	public String getBigPicLink() {
		return this.bigPicLink;
	}

	public void setBigPicLink(String bigPicLink) {
		this.bigPicLink = bigPicLink;
	}

	@Column(name = "payment_time", length = 30)
	public String getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(String paymentTime) {
		this.paymentTime = paymentTime;
	}


	@Column(name = "delivery_date", length = 30)
	public String getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(String deliveryDate) {
		this.deliveryDate = deliveryDate;
	}
	
	@Column(name = "hospital_presc_date", length = 30)
	public String getHospitalPrescDate() {
		return hospitalPrescDate;
	}

	public void setHospitalPrescDate(String hospitalPrescDate) {
		this.hospitalPrescDate = hospitalPrescDate;
	}


	@Column(name = "address_detail", nullable = false, length = 200)
	public String getAddressDetail() {
		return this.addressDetail;
	}

	public void setAddressDetail(String addressDetail) {
		this.addressDetail = addressDetail;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "province", length = 50)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Column(name = "area", length = 50)
	public String getArea() {
		return area;
	}


	public void setArea(String area) {
		this.area = area;
	}


	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "order_price", nullable = false, precision = 13, scale = 4)
	public BigDecimal getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "discount_amount", precision = 13, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}
	

	@Column(name = "over_return_free", precision = 13, scale = 4)
	public BigDecimal getOverReturnFree() {
		return overReturnFree;
	}


	public void setOverReturnFree(BigDecimal overReturnFree) {
		this.overReturnFree = overReturnFree;
	}

	@Column(name = "express_price", precision = 13, scale = 4)
	public BigDecimal getExpressPrice() {
		return expressPrice;
	}


	public void setExpressPrice(BigDecimal expressPrice) {
		this.expressPrice = expressPrice;
	}

	@Column(name = "plat_pay_price", precision = 13, scale = 4)
	public BigDecimal getPlatPayPrice() {
		return platPayPrice;
	}


	public void setPlatPayPrice(BigDecimal platPayPrice) {
		this.platPayPrice = platPayPrice;
	}


	@Column(name = "instructions", length = 2000)
	public String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(String instructions) {
		this.instructions = instructions;
	}


	@Column(name = "remark", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "fee_type", length = 20)
	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	@Column(name = "last_time", length = 30)
	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
