package com.ehaoyao.opertioncenter.thirdOrderAudit.model;
// Generated 2016-1-11 1:31:23 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail")
public class OrderDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6817380451359498596L;
	private Long orderDetailId;
	private String orderNumber;
	private String merchantId;
	private String productId;
	private String productName;
	private BigDecimal totalPrice;
	private String productSpec;
	private String productBrand;
	private Integer packCount;
	private Integer count;
	private BigDecimal price;
	private String unit;
	private Character giftFlag;
	private Character prescriptionType;
	private String productLicenseNo;
	private String pharmacyCompany;
	private BigDecimal discountAmount;
	private String createTime;
	private String lastTime;

	public OrderDetail() {
	}

	public OrderDetail(String orderNumber, String merchantId, String productName) {
		this.orderNumber = orderNumber;
		this.merchantId = merchantId;
		this.productName = productName;
	}

	public OrderDetail(String orderNumber, String merchantId, String productId, String productName,
			BigDecimal totalPrice, String productSpec, String productBrand, Integer packCount, Integer count,
			BigDecimal price, String unit, Character giftFlag, Character prescriptionType, String productLicenseNo,
			String pharmacyCompany, BigDecimal discountAmount, String createTime, String lastTime) {
		this.orderNumber = orderNumber;
		this.merchantId = merchantId;
		this.productId = productId;
		this.productName = productName;
		this.totalPrice = totalPrice;
		this.productSpec = productSpec;
		this.productBrand = productBrand;
		this.packCount = packCount;
		this.count = count;
		this.price = price;
		this.unit = unit;
		this.giftFlag = giftFlag;
		this.prescriptionType = prescriptionType;
		this.productLicenseNo = productLicenseNo;
		this.pharmacyCompany = pharmacyCompany;
		this.discountAmount = discountAmount;
		this.createTime = createTime;
		this.lastTime = lastTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_detail_id", unique = true, nullable = false)
	public Long getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(Long orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	@Column(name = "order_number", nullable = false, length = 50)
	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "merchant_id", nullable = false, length = 50)
	public String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "product_id", length = 50)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "total_price", precision = 13, scale = 4)
	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "product_spec", length = 100)
	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	@Column(name = "product_brand", length = 100)
	public String getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(String productBrand) {
		this.productBrand = productBrand;
	}

	@Column(name = "pack_count")
	public Integer getPackCount() {
		return this.packCount;
	}

	public void setPackCount(Integer packCount) {
		this.packCount = packCount;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "price", precision = 10, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "unit", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "gift_flag", length = 1)
	public Character getGiftFlag() {
		return this.giftFlag;
	}

	public void setGiftFlag(Character giftFlag) {
		this.giftFlag = giftFlag;
	}

	@Column(name = "prescription_type", length = 1)
	public Character getPrescriptionType() {
		return this.prescriptionType;
	}

	public void setPrescriptionType(Character prescriptionType) {
		this.prescriptionType = prescriptionType;
	}

	@Column(name = "product_license_no", length = 100)
	public String getProductLicenseNo() {
		return this.productLicenseNo;
	}

	public void setProductLicenseNo(String productLicenseNo) {
		this.productLicenseNo = productLicenseNo;
	}

	@Column(name = "pharmacy_company", length = 100)
	public String getPharmacyCompany() {
		return this.pharmacyCompany;
	}

	public void setPharmacyCompany(String pharmacyCompany) {
		this.pharmacyCompany = pharmacyCompany;
	}

	@Column(name = "discount_amount", precision = 10, scale = 4)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "last_time", length = 30)
	public String getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

}
