package com.ehaoyao.opertioncenter.thirdOrderAudit.model;
// Generated 2016-1-11 1:31:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPartner generated by hbm2java
 */
@Entity
@Table(name = "tb_partner", catalog = "operationscenter")
public class TbPartner implements java.io.Serializable {

	private Long tbPartnerId;
	private String fdUuid;
	private String partnerKey;
	private char status;

	public TbPartner() {
	}

	public TbPartner(String fdUuid, String partnerKey, char status) {
		this.fdUuid = fdUuid;
		this.partnerKey = partnerKey;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tb_partner_id", unique = true, nullable = false)
	public Long getTbPartnerId() {
		return this.tbPartnerId;
	}

	public void setTbPartnerId(Long tbPartnerId) {
		this.tbPartnerId = tbPartnerId;
	}

	@Column(name = "fd_uuid", nullable = false, length = 20)
	public String getFdUuid() {
		return this.fdUuid;
	}

	public void setFdUuid(String fdUuid) {
		this.fdUuid = fdUuid;
	}

	@Column(name = "partner_key", nullable = false, length = 32)
	public String getPartnerKey() {
		return this.partnerKey;
	}

	public void setPartnerKey(String partnerKey) {
		this.partnerKey = partnerKey;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
